### ISSUE TITLE
Issues running on Windows

### ISSUE THREAD

**Issue by CedarDCX** [google-developer-training/pwa-ecommerce-demo#9]
Reading the error logs, it appears python is a dependency, although this is not mentioned in the readme.

Once python is installed, `serve` still doesn't work as node-sass is not supported on Windows 64-bit with unsupported runtime.

**Comment by nasearle** [comment]
I added Python as a dependency in the readme. Thanks for the suggestion!

Sorry to hear it's not working! I checked the [node-sass documentation](https://www.npmjs.com/package/node-sass) and it mentions that you need to have Visual Studio 2013 for versions 0.9.4 and above. Do you have that installed and do you think that might be causing the issue?

We'll try and address this soon but please let us know if you get it working!

**Comment by satyakresna** [comment]
Hi, I got also issue running on Windows (7 64-bit). But, I think my problem is different. I'm already install python dan then run ```npm run serve``` print out these errors:
```
[17:12:50] Failed to load external module babel-register
[17:12:50] Failed to load external module babel-core/register
[17:12:50] Failed to load external module babel/register
[17:12:50] Local gulp not found in ~\Documents\Try PWA\pwa-ecommerce-demo\project
[17:12:50] Try running: npm install gulp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serv
e"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ serve: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ serve script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
```
Next, I try to install ```gulp``` and run ```gulp serve``` and print out these errors:
```
[17:48:21] Failed to load external module babel-register
[17:48:21] Failed to load external module babel-core/register
[17:48:21] Failed to load external module babel/register
C:\Users\satyakresna\Documents\Try PWA\pwa-ecommerce-demo\project\gulpfile.babel.js:30
import path from 'path';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at execute (C:\Users\satyakresna\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:26:18)
    at Liftoff.handleArguments (C:\Users\satyakresna\AppData\Roaming\npm\node_modules\gulp-cli\index.js:173:63)
```

**Comment by nasearle** [comment]
Hi Satya, that does look like a different issue. You need to run just `npm install` to install the babel modules. They are included as dependencies in the package.json

**Comment by satyakresna** [comment]
Hi nasearle, alright. Thank you
